name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish application
      run: dotnet publish -c Release -o ./Publish

    - name: Zip Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'ScreenshareHelper-release.zip'
        directory: './src/Publish'
        exclusions: '*.deps.json *.pdb'

    - uses: bhowell2/github-substring-action@master
      id: get-branch-name
      with:
        value: ${{github.ref}}
        index_of_str: "refs/heads/"

    - name: Create or Update tag
      run: |
        git tag -f ${{steps.get-branch-name.outputs.substring}}Build
        git push -f origin ${{steps.get-branch-name.outputs.substring}}Build

    - name: List files
      run: |
        Get-ChildItem -Recurse

    - name: Archive everything
      uses: actions/upload-artifact@v3
      with:
        name: Everything
        path: .

    - name: Upload Release
      uses: ncipollo/release-action@main
      with:
        name: Release ${{steps.get-branch-name.outputs.substring}}
        tag: ${{steps.get-branch-name.outputs.substring}}Build
        allowUpdates: true
        prerelease: false
        removeArtifacts: true
        replacesArtifacts: true
        artifactErrorsFailBuild: true
        artifacts: ./src/Publish/ScreenshareHelper-release.zip
        artifactContentType: application/zip
        token: ${{ secrets.GITHUB_TOKEN }}
