name: .NET

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Load version number from tag
    - uses: bhowell2/github-substring-action@master
      id: branch-name
      with:
        value: ${{github.ref}}
        index_of_str: "refs/tags/"

    # Replace version number
    - name: Replace version number
      uses: thiagodnf/string-replacer@v1.0.2
      with:
        find: <Version>1.0.0</Version>
        replace: <Version>${{steps.branch-name.outputs.substring}}</Version>
        include: src/ScreenshareHelper/ScreenshareHelper.csproj

    # Build solution
    - name: Restore dependencies
      run: |
        cd src
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd src
        dotnet test --no-build --verbosity normal
    - name: Publish application
      run: |
        cd src
        dotnet publish -c Release -o ./Publish

    # Build installer
    - name: Create nsis installer
      uses: joncloud/makensis-action@publish
      with:
        script-file: installer.nsi
    - name: Rename installer
      run: mv ScreenshareHelperInstaller.exe ScreenshareHelperInstaller-${{steps.branch-name.outputs.substring}}.exe

    - name: List files
      run: |
        Get-ChildItem -Recurse

    # Create Zip
    - name: Zip Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'ScreenshareHelper-release.zip'
        directory: './src/Publish'
        exclusions: '*.deps.json *.pdb'

    - name: List files
      run: |
        Get-ChildItem -Recurse

    # Create Release
    - name: Upload Release
      uses: ncipollo/release-action@main
      with:
        name: Release ${{steps.branch-name.outputs.substring}}
        allowUpdates: true
        prerelease: false
        removeArtifacts: true
        replacesArtifacts: true
        artifactErrorsFailBuild: true
        artifacts: "ScreenshareHelperInstaller-${{steps.branch-name.outputs.substring}}.exe,src/Publish/ScreenshareHelper-release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
